# Generated by Django 5.0.6 on 2024-06-22 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('ssk_flag', models.CharField(max_length=100)),
                ('robot_update_flag', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator_app.machine')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator_app.robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator_app.user')),
            ],
        ),
    ]
