# Generated by Django 5.0.6 on 2024-06-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_app', '0002_alter_process_result_alter_process_robot_update_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='bot',
            new_name='robot',
        ),
    ]
