# Generated by Django 5.0.6 on 2024-06-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_app', '0003_rename_bot_process_robot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='robot',
            new_name='bot',
        ),
    ]
