# Generated by Django 5.0.6 on 2024-06-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_app', '0004_rename_robot_process_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='bot',
            new_name='robot',
        ),
    ]
