# Generated by Django 5.0.6 on 2024-06-22 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_app', '0005_rename_bot_process_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator_app.user'),
        ),
    ]
