# Generated by Django 5.0.6 on 2024-06-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_app', '0006_alter_process_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator_app.user', unique=True),
        ),
    ]
