# Generated by Django 5.0.6 on 2024-06-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_app', '0008_alter_machine_machine_name_alter_process_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='robot_zip_files'),
        ),
        migrations.AddField(
            model_name='robot',
            name='zip_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
