# Generated by Django 5.0.6 on 2024-06-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_app', '0009_robot_zip_file_robot_zip_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='zip_name',
        ),
        migrations.AlterField(
            model_name='robot',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zip_files'),
        ),
    ]
